// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: dbcache.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DBCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBCacheRequest) Reset() {
	*x = DBCacheRequest{}
	mi := &file_dbcache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBCacheRequest) ProtoMessage() {}

func (x *DBCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbcache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBCacheRequest.ProtoReflect.Descriptor instead.
func (*DBCacheRequest) Descriptor() ([]byte, []int) {
	return file_dbcache_proto_rawDescGZIP(), []int{0}
}

func (x *DBCacheRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

type DBCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	FromCache     bool                   `protobuf:"varint,2,opt,name=from_cache,json=fromCache,proto3" json:"from_cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBCacheResponse) Reset() {
	*x = DBCacheResponse{}
	mi := &file_dbcache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBCacheResponse) ProtoMessage() {}

func (x *DBCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbcache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBCacheResponse.ProtoReflect.Descriptor instead.
func (*DBCacheResponse) Descriptor() ([]byte, []int) {
	return file_dbcache_proto_rawDescGZIP(), []int{1}
}

func (x *DBCacheResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *DBCacheResponse) GetFromCache() bool {
	if x != nil {
		return x.FromCache
	}
	return false
}

var File_dbcache_proto protoreflect.FileDescriptor

const file_dbcache_proto_rawDesc = "" +
	"\n" +
	"\rdbcache.proto\x12\adbcache\"+\n" +
	"\x0eDBCacheRequest\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\"D\n" +
	"\x0fDBCacheResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12\x1d\n" +
	"\n" +
	"from_cache\x18\x02 \x01(\bR\tfromCache2N\n" +
	"\x0eDBCacheService\x12<\n" +
	"\aGetData\x12\x17.dbcache.DBCacheRequest\x1a\x18.dbcache.DBCacheResponseB\vZ\t/genprotob\x06proto3"

var (
	file_dbcache_proto_rawDescOnce sync.Once
	file_dbcache_proto_rawDescData []byte
)

func file_dbcache_proto_rawDescGZIP() []byte {
	file_dbcache_proto_rawDescOnce.Do(func() {
		file_dbcache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dbcache_proto_rawDesc), len(file_dbcache_proto_rawDesc)))
	})
	return file_dbcache_proto_rawDescData
}

var file_dbcache_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dbcache_proto_goTypes = []any{
	(*DBCacheRequest)(nil),  // 0: dbcache.DBCacheRequest
	(*DBCacheResponse)(nil), // 1: dbcache.DBCacheResponse
}
var file_dbcache_proto_depIdxs = []int32{
	0, // 0: dbcache.DBCacheService.GetData:input_type -> dbcache.DBCacheRequest
	1, // 1: dbcache.DBCacheService.GetData:output_type -> dbcache.DBCacheResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dbcache_proto_init() }
func file_dbcache_proto_init() {
	if File_dbcache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dbcache_proto_rawDesc), len(file_dbcache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dbcache_proto_goTypes,
		DependencyIndexes: file_dbcache_proto_depIdxs,
		MessageInfos:      file_dbcache_proto_msgTypes,
	}.Build()
	File_dbcache_proto = out.File
	file_dbcache_proto_goTypes = nil
	file_dbcache_proto_depIdxs = nil
}
