syntax = "proto3";

package dbcache;
option go_package = "/pkg/protobuf";
import "google/protobuf/empty.proto";

// Message to define a parameterized sql query.
message FallbackQuery {
  string query = 1;
  repeated string args = 2;
}

// Request message for retrieving data.
message GetRequest {
  string query_id = 1; // Key of data to be retrieved from cache.
  FallbackQuery fallback_query = 2; // query to hit DB if cache miss.
  bool skip_cache = 3; // Skip cache, go straight to DB.
}
// Response message for retrieving data.
message GetResponse {
  bool from_cache = 1; // True if from cache.
  bytes data = 2; // Data from cache/db.
  int64 ttl_seconds = 3; // Remaining TTL if cached.
}

message InsertRequest {
  string query_id = 1;  // Key of data to be cached.
  bytes data = 2;  // Data to be cached.
  int64 ttl_seconds = 3; // Time to live in seconds
}
message InsertResponse {
  bool success = 1; 
}

message InvalidateRequest {
  repeated string keys = 1; // One or more cache keys to invalidate
}

message InvalidateResponse {
  int64 entries_removed = 1;
}

message FlushRequest {
  bool confirm = 1; // Opt-in is explicit.
}
message FlushResponse {
  int64 number_of_entries_removed = 1;
}

message HealthCheckResponse {
  bool healthy = 1;
  string cache_error = 2;
  string db_error = 3;
}

service DBCacheService {
  // GetData: Retrieve data from cache if available. Else run fallback query and cache the result.
  rpc GetData(GetRequest) returns (GetResponse);
  // InsertData: Manually insert data into cache.
  rpc InsertData(InsertRequest) returns (InsertResponse);
  // InvalidateCache: remove key(s) from cache.
  rpc InvalidateCache(InvalidateRequest) returns (InvalidateResponse);
  // FlushCache: remove all entries from cache.
  rpc FlushCache(FlushRequest) returns (FlushResponse);
  // Server returns healthy, pings status of db and cache.
  rpc CheckHealth(google.protobuf.Empty) returns (HealthCheckResponse);
}
