// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: dbcache.proto

package protobuf

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message to define a parameterized sql query.
type FallbackQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FallbackQuery) Reset() {
	*x = FallbackQuery{}
	mi := &file_dbcache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FallbackQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FallbackQuery) ProtoMessage() {}

func (x *FallbackQuery) ProtoReflect() protoreflect.Message {
	mi := &file_dbcache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FallbackQuery.ProtoReflect.Descriptor instead.
func (*FallbackQuery) Descriptor() ([]byte, []int) {
	return file_dbcache_proto_rawDescGZIP(), []int{0}
}

func (x *FallbackQuery) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *FallbackQuery) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

// Request message for retrieving data.
type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`                   // Key of data to be retrieved from cache.
	FallbackQuery *FallbackQuery         `protobuf:"bytes,2,opt,name=fallback_query,json=fallbackQuery,proto3" json:"fallback_query,omitempty"` // query to hit DB if cache miss.
	SkipCache     bool                   `protobuf:"varint,3,opt,name=skip_cache,json=skipCache,proto3" json:"skip_cache,omitempty"`            // Skip cache, go straight to DB.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_dbcache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbcache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_dbcache_proto_rawDescGZIP(), []int{1}
}

func (x *GetRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *GetRequest) GetFallbackQuery() *FallbackQuery {
	if x != nil {
		return x.FallbackQuery
	}
	return nil
}

func (x *GetRequest) GetSkipCache() bool {
	if x != nil {
		return x.SkipCache
	}
	return false
}

// Response message for retrieving data.
type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromCache     bool                   `protobuf:"varint,1,opt,name=from_cache,json=fromCache,proto3" json:"from_cache,omitempty"`    // True if from cache.
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                                // Data from cache/db.
	TtlSeconds    int64                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"` // Remaining TTL if cached.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_dbcache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbcache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_dbcache_proto_rawDescGZIP(), []int{2}
}

func (x *GetResponse) GetFromCache() bool {
	if x != nil {
		return x.FromCache
	}
	return false
}

func (x *GetResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetResponse) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type InsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`           // Key of data to be cached.
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                                // Data to be cached.
	TtlSeconds    int64                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"` // Time to live in seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	mi := &file_dbcache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbcache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_dbcache_proto_rawDescGZIP(), []int{3}
}

func (x *InsertRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *InsertRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *InsertRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type InsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	mi := &file_dbcache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbcache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_dbcache_proto_rawDescGZIP(), []int{4}
}

func (x *InsertResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type InvalidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"` // One or more cache keys to invalidate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateRequest) Reset() {
	*x = InvalidateRequest{}
	mi := &file_dbcache_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateRequest) ProtoMessage() {}

func (x *InvalidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbcache_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateRequest.ProtoReflect.Descriptor instead.
func (*InvalidateRequest) Descriptor() ([]byte, []int) {
	return file_dbcache_proto_rawDescGZIP(), []int{5}
}

func (x *InvalidateRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type InvalidateResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EntriesRemoved int64                  `protobuf:"varint,1,opt,name=entries_removed,json=entriesRemoved,proto3" json:"entries_removed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InvalidateResponse) Reset() {
	*x = InvalidateResponse{}
	mi := &file_dbcache_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateResponse) ProtoMessage() {}

func (x *InvalidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbcache_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateResponse.ProtoReflect.Descriptor instead.
func (*InvalidateResponse) Descriptor() ([]byte, []int) {
	return file_dbcache_proto_rawDescGZIP(), []int{6}
}

func (x *InvalidateResponse) GetEntriesRemoved() int64 {
	if x != nil {
		return x.EntriesRemoved
	}
	return 0
}

type FlushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Confirm       bool                   `protobuf:"varint,1,opt,name=confirm,proto3" json:"confirm,omitempty"` // Opt-in is explicit.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushRequest) Reset() {
	*x = FlushRequest{}
	mi := &file_dbcache_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushRequest) ProtoMessage() {}

func (x *FlushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbcache_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushRequest.ProtoReflect.Descriptor instead.
func (*FlushRequest) Descriptor() ([]byte, []int) {
	return file_dbcache_proto_rawDescGZIP(), []int{7}
}

func (x *FlushRequest) GetConfirm() bool {
	if x != nil {
		return x.Confirm
	}
	return false
}

type FlushResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	NumberOfEntriesRemoved int64                  `protobuf:"varint,1,opt,name=number_of_entries_removed,json=numberOfEntriesRemoved,proto3" json:"number_of_entries_removed,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FlushResponse) Reset() {
	*x = FlushResponse{}
	mi := &file_dbcache_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushResponse) ProtoMessage() {}

func (x *FlushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbcache_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushResponse.ProtoReflect.Descriptor instead.
func (*FlushResponse) Descriptor() ([]byte, []int) {
	return file_dbcache_proto_rawDescGZIP(), []int{8}
}

func (x *FlushResponse) GetNumberOfEntriesRemoved() int64 {
	if x != nil {
		return x.NumberOfEntriesRemoved
	}
	return 0
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	CacheError    string                 `protobuf:"bytes,2,opt,name=cache_error,json=cacheError,proto3" json:"cache_error,omitempty"`
	DbError       string                 `protobuf:"bytes,3,opt,name=db_error,json=dbError,proto3" json:"db_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_dbcache_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbcache_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_dbcache_proto_rawDescGZIP(), []int{9}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetCacheError() string {
	if x != nil {
		return x.CacheError
	}
	return ""
}

func (x *HealthCheckResponse) GetDbError() string {
	if x != nil {
		return x.DbError
	}
	return ""
}

var File_dbcache_proto protoreflect.FileDescriptor

const file_dbcache_proto_rawDesc = "" +
	"\n" +
	"\rdbcache.proto\x12\adbcache\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\"9\n" +
	"\rFallbackQuery\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\"\x85\x01\n" +
	"\n" +
	"GetRequest\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12=\n" +
	"\x0efallback_query\x18\x02 \x01(\v2\x16.dbcache.FallbackQueryR\rfallbackQuery\x12\x1d\n" +
	"\n" +
	"skip_cache\x18\x03 \x01(\bR\tskipCache\"a\n" +
	"\vGetResponse\x12\x1d\n" +
	"\n" +
	"from_cache\x18\x01 \x01(\bR\tfromCache\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\"_\n" +
	"\rInsertRequest\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\"*\n" +
	"\x0eInsertResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"'\n" +
	"\x11InvalidateRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\"=\n" +
	"\x12InvalidateResponse\x12'\n" +
	"\x0fentries_removed\x18\x01 \x01(\x03R\x0eentriesRemoved\"(\n" +
	"\fFlushRequest\x12\x18\n" +
	"\aconfirm\x18\x01 \x01(\bR\aconfirm\"J\n" +
	"\rFlushResponse\x129\n" +
	"\x19number_of_entries_removed\x18\x01 \x01(\x03R\x16numberOfEntriesRemoved\"k\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x1f\n" +
	"\vcache_error\x18\x02 \x01(\tR\n" +
	"cacheError\x12\x19\n" +
	"\bdb_error\x18\x03 \x01(\tR\adbError2\x93\x03\n" +
	"\x0eDBCacheService\x12I\n" +
	"\aGetData\x12\x13.dbcache.GetRequest\x1a\x14.dbcache.GetResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/data\x12T\n" +
	"\n" +
	"InsertData\x12\x16.dbcache.InsertRequest\x1a\x17.dbcache.InsertResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/insert\x12J\n" +
	"\x0fInvalidateCache\x12\x1a.dbcache.InvalidateRequest\x1a\x1b.dbcache.InvalidateResponse\x12;\n" +
	"\n" +
	"FlushCache\x12\x15.dbcache.FlushRequest\x1a\x16.dbcache.FlushResponse\x12W\n" +
	"\vCheckHealth\x12\x16.google.protobuf.Empty\x1a\x1c.dbcache.HealthCheckResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/healthB\x0fZ\r/pkg/protobufb\x06proto3"

var (
	file_dbcache_proto_rawDescOnce sync.Once
	file_dbcache_proto_rawDescData []byte
)

func file_dbcache_proto_rawDescGZIP() []byte {
	file_dbcache_proto_rawDescOnce.Do(func() {
		file_dbcache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dbcache_proto_rawDesc), len(file_dbcache_proto_rawDesc)))
	})
	return file_dbcache_proto_rawDescData
}

var file_dbcache_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_dbcache_proto_goTypes = []any{
	(*FallbackQuery)(nil),       // 0: dbcache.FallbackQuery
	(*GetRequest)(nil),          // 1: dbcache.GetRequest
	(*GetResponse)(nil),         // 2: dbcache.GetResponse
	(*InsertRequest)(nil),       // 3: dbcache.InsertRequest
	(*InsertResponse)(nil),      // 4: dbcache.InsertResponse
	(*InvalidateRequest)(nil),   // 5: dbcache.InvalidateRequest
	(*InvalidateResponse)(nil),  // 6: dbcache.InvalidateResponse
	(*FlushRequest)(nil),        // 7: dbcache.FlushRequest
	(*FlushResponse)(nil),       // 8: dbcache.FlushResponse
	(*HealthCheckResponse)(nil), // 9: dbcache.HealthCheckResponse
	(*emptypb.Empty)(nil),       // 10: google.protobuf.Empty
}
var file_dbcache_proto_depIdxs = []int32{
	0,  // 0: dbcache.GetRequest.fallback_query:type_name -> dbcache.FallbackQuery
	1,  // 1: dbcache.DBCacheService.GetData:input_type -> dbcache.GetRequest
	3,  // 2: dbcache.DBCacheService.InsertData:input_type -> dbcache.InsertRequest
	5,  // 3: dbcache.DBCacheService.InvalidateCache:input_type -> dbcache.InvalidateRequest
	7,  // 4: dbcache.DBCacheService.FlushCache:input_type -> dbcache.FlushRequest
	10, // 5: dbcache.DBCacheService.CheckHealth:input_type -> google.protobuf.Empty
	2,  // 6: dbcache.DBCacheService.GetData:output_type -> dbcache.GetResponse
	4,  // 7: dbcache.DBCacheService.InsertData:output_type -> dbcache.InsertResponse
	6,  // 8: dbcache.DBCacheService.InvalidateCache:output_type -> dbcache.InvalidateResponse
	8,  // 9: dbcache.DBCacheService.FlushCache:output_type -> dbcache.FlushResponse
	9,  // 10: dbcache.DBCacheService.CheckHealth:output_type -> dbcache.HealthCheckResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_dbcache_proto_init() }
func file_dbcache_proto_init() {
	if File_dbcache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dbcache_proto_rawDesc), len(file_dbcache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dbcache_proto_goTypes,
		DependencyIndexes: file_dbcache_proto_depIdxs,
		MessageInfos:      file_dbcache_proto_msgTypes,
	}.Build()
	File_dbcache_proto = out.File
	file_dbcache_proto_goTypes = nil
	file_dbcache_proto_depIdxs = nil
}
