// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: dbcache.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DBCacheService_GetData_FullMethodName         = "/dbcache.DBCacheService/GetData"
	DBCacheService_InsertData_FullMethodName      = "/dbcache.DBCacheService/InsertData"
	DBCacheService_InvalidateCache_FullMethodName = "/dbcache.DBCacheService/InvalidateCache"
	DBCacheService_FlushCache_FullMethodName      = "/dbcache.DBCacheService/FlushCache"
	DBCacheService_CheckHealth_FullMethodName     = "/dbcache.DBCacheService/CheckHealth"
)

// DBCacheServiceClient is the client API for DBCacheService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DBCacheServiceClient interface {
	// GetData: Retrieve data from cache if available. Else run fallback query and cache the result.
	// Need to use post so we can send the fallback query as a json body.
	GetData(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// InsertData: Manually insert data into cache.
	InsertData(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error)
	// InvalidateCache: remove key(s) from cache.
	InvalidateCache(ctx context.Context, in *InvalidateRequest, opts ...grpc.CallOption) (*InvalidateResponse, error)
	// FlushCache: remove all entries from cache.
	FlushCache(ctx context.Context, in *FlushRequest, opts ...grpc.CallOption) (*FlushResponse, error)
	// Server returns healthy, pings status of db and cache.
	CheckHealth(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type dBCacheServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDBCacheServiceClient(cc grpc.ClientConnInterface) DBCacheServiceClient {
	return &dBCacheServiceClient{cc}
}

func (c *dBCacheServiceClient) GetData(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, DBCacheService_GetData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBCacheServiceClient) InsertData(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertResponse)
	err := c.cc.Invoke(ctx, DBCacheService_InsertData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBCacheServiceClient) InvalidateCache(ctx context.Context, in *InvalidateRequest, opts ...grpc.CallOption) (*InvalidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvalidateResponse)
	err := c.cc.Invoke(ctx, DBCacheService_InvalidateCache_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBCacheServiceClient) FlushCache(ctx context.Context, in *FlushRequest, opts ...grpc.CallOption) (*FlushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlushResponse)
	err := c.cc.Invoke(ctx, DBCacheService_FlushCache_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBCacheServiceClient) CheckHealth(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, DBCacheService_CheckHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DBCacheServiceServer is the server API for DBCacheService service.
// All implementations must embed UnimplementedDBCacheServiceServer
// for forward compatibility.
type DBCacheServiceServer interface {
	// GetData: Retrieve data from cache if available. Else run fallback query and cache the result.
	// Need to use post so we can send the fallback query as a json body.
	GetData(context.Context, *GetRequest) (*GetResponse, error)
	// InsertData: Manually insert data into cache.
	InsertData(context.Context, *InsertRequest) (*InsertResponse, error)
	// InvalidateCache: remove key(s) from cache.
	InvalidateCache(context.Context, *InvalidateRequest) (*InvalidateResponse, error)
	// FlushCache: remove all entries from cache.
	FlushCache(context.Context, *FlushRequest) (*FlushResponse, error)
	// Server returns healthy, pings status of db and cache.
	CheckHealth(context.Context, *emptypb.Empty) (*HealthCheckResponse, error)
	mustEmbedUnimplementedDBCacheServiceServer()
}

// UnimplementedDBCacheServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDBCacheServiceServer struct{}

func (UnimplementedDBCacheServiceServer) GetData(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetData not implemented")
}
func (UnimplementedDBCacheServiceServer) InsertData(context.Context, *InsertRequest) (*InsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertData not implemented")
}
func (UnimplementedDBCacheServiceServer) InvalidateCache(context.Context, *InvalidateRequest) (*InvalidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvalidateCache not implemented")
}
func (UnimplementedDBCacheServiceServer) FlushCache(context.Context, *FlushRequest) (*FlushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FlushCache not implemented")
}
func (UnimplementedDBCacheServiceServer) CheckHealth(context.Context, *emptypb.Empty) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckHealth not implemented")
}
func (UnimplementedDBCacheServiceServer) mustEmbedUnimplementedDBCacheServiceServer() {}
func (UnimplementedDBCacheServiceServer) testEmbeddedByValue()                        {}

// UnsafeDBCacheServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DBCacheServiceServer will
// result in compilation errors.
type UnsafeDBCacheServiceServer interface {
	mustEmbedUnimplementedDBCacheServiceServer()
}

func RegisterDBCacheServiceServer(s grpc.ServiceRegistrar, srv DBCacheServiceServer) {
	// If the following call pancis, it indicates UnimplementedDBCacheServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DBCacheService_ServiceDesc, srv)
}

func _DBCacheService_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBCacheServiceServer).GetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBCacheService_GetData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBCacheServiceServer).GetData(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBCacheService_InsertData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBCacheServiceServer).InsertData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBCacheService_InsertData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBCacheServiceServer).InsertData(ctx, req.(*InsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBCacheService_InvalidateCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvalidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBCacheServiceServer).InvalidateCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBCacheService_InvalidateCache_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBCacheServiceServer).InvalidateCache(ctx, req.(*InvalidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBCacheService_FlushCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBCacheServiceServer).FlushCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBCacheService_FlushCache_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBCacheServiceServer).FlushCache(ctx, req.(*FlushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBCacheService_CheckHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBCacheServiceServer).CheckHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBCacheService_CheckHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBCacheServiceServer).CheckHealth(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// DBCacheService_ServiceDesc is the grpc.ServiceDesc for DBCacheService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DBCacheService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dbcache.DBCacheService",
	HandlerType: (*DBCacheServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetData",
			Handler:    _DBCacheService_GetData_Handler,
		},
		{
			MethodName: "InsertData",
			Handler:    _DBCacheService_InsertData_Handler,
		},
		{
			MethodName: "InvalidateCache",
			Handler:    _DBCacheService_InvalidateCache_Handler,
		},
		{
			MethodName: "FlushCache",
			Handler:    _DBCacheService_FlushCache_Handler,
		},
		{
			MethodName: "CheckHealth",
			Handler:    _DBCacheService_CheckHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dbcache.proto",
}
