syntax = "proto3";

package dbcache;
option go_package = "/internal/genproto";

// Empty message for when no input parameter is needed.
message Empty {}

// Request message for retrieving data.
message GetRequest {
  string key = 1; // Key of data to be retrieved from cache.
}

// Response message for retrieving data.
message GetResponse {
  bytes data = 1; // Data from cache/db.
  int64 ttl_seconds = 2; // Remaining TTL.
}

message InsertRequest {
  string key = 1;  // Key of data to be cached.
  bytes data = 2;  // Data to be cached.
  int64 ttl_seconds = 3; // Time to live in seconds
}

message InsertResponse {
  bool success = 1; 
  string error = 2; // if there was a failure.``
}

message HealthCheckResponse {
  bool healthy = 1;
}

message FlushRequest {
  bool confirm = 1; // Opt-in is explicit.
}
message FlushResponse {
  bool success = 1;
  int64 number_of_entries_removed = 2;
}

service DBCacheService {
  rpc GetData(GetRequest) returns (GetResponse);
  rpc InsertData(InsertRequest) returns (InsertResponse);
  rpc CheckHealth(Empty) returns (HealthCheckResponse);
  rpc FlushCache(FlushRequest) returns (FlushResponse);
}
